// Dynamic game data array — swap this for an API/CMS call once the backend is ready.
// Screenshots are served directly from public/Webp/<Game Name>/ (one folder per game).

export const categories = ["All Games", "Action", "Racing", "RPG", "Adventure", "Multiplayer", "Mobile"];

export const games = [
  {
    id: 1,
    slug: "barber-shop-simulator",
    icon: "/icons/Barber Haircut.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.BarberHaircutShop",
    youtubeUrl: null, // TODO: add trailer link
    title: "Barber Shop Simulator",
    genre: "Simulation",
    categories: ["Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5, 6, 7].map((n) => `/Webp/Barber Haircut Shop Game/${n}.webp`),
    description: "Run your own barber shop — cut, shave, style and satisfy a stream of quirky customers in this relaxing, satisfying simulation game.",
    features: ["Realistic Styling Tools", "Customer Progression", "Shop Upgrades", "Relaxing Gameplay"],
    platforms: ["Mobile"],
    tech: ["Unity", "C++"],
    status: "Live",
    rating: 4.6,
    downloads: "10K+",
  },
  {
    id: 2,
    slug: "custom-diy-phone-case-maker",
    icon: "/icons/Custom Di Phone.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.CustomDIYPhoneCaseMaker",
    youtubeUrl: null, // TODO: add trailer link
    title: "Custom DIY Phone Case Maker",
    genre: "Casual Creation",
    categories: ["Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5, 6].map((n) => `/Webp/Custom Diy Phone Case Maker/${n}.webp`),
    description: "Design and craft your own phone cases with endless colors, stickers and charms in this creative, ASMR-inspired casual experience.",
    features: ["Endless Customization", "ASMR Sound Design", "Sticker & Charm Packs", "Satisfying Crafting Loop"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.5,
    downloads: "8K+",
  },
  {
    id: 3,
    slug: "fireworks-simulator-2025",
    icon: "/icons/Fireworks.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.FireworkSimulator2025",
    youtubeUrl: null, // TODO: add trailer link
    title: "Fireworks Simulator 2025",
    genre: "Simulation",
    categories: ["Action", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Fireworks Games Simulator 2025/${n}.webp`),
    description: "Design your dream Diwali or New Year show with stunning 3D fireworks, explosive ASMR sound design and an open-world city to light up.",
    features: ["Open World", "Explosive FX", "Festival Fun", "Realistic Physics"],
    platforms: ["Mobile"],
    tech: ["Unity", "C++"],
    status: "Live",
    rating: 4.9,
    downloads: "30K+",
  },
  {
    id: 4,
    slug: "flappy-sky-cloud-runner",
    icon: "/icons/Flapy Cloudy.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.FlappyCloudy",
    youtubeUrl: null, // TODO: add trailer link
    title: "Flappy Sky Cloud Runner",
    genre: "Endless Runner",
    categories: ["Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 6].map((n) => `/Webp/Flappy Sky Cloud Runner/${n}.webp`),
    description: "Tap to fly through a dynamic sky, dodge birds and unlock adorable cloud skins in this addictive one-more-try runner.",
    features: ["Tap-to-Fly", "Unlockable Skins", "Dynamic Weather", "Endless Fun"],
    platforms: ["Mobile"],
    tech: ["Unity", "C++"],
    status: "Live",
    rating: 4.6,
    downloads: "5K+",
  },
  {
    id: 5,
    slug: "home-makeover-asmr-cleaning",
    icon: "/icons/Home Makeover.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.Eraflip.HomeMakeoverASMRCleaning",
    youtubeUrl: null, // TODO: add trailer link
    title: "Home Makeover ASMR Cleaning",
    genre: "Simulation",
    categories: ["Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Home Makeover ASMR Cleaning/${n}.webp`),
    description: "Restore messy, cluttered rooms to spotless perfection with soothing ASMR cleaning sounds and satisfying before-and-after makeovers.",
    features: ["ASMR Sound Design", "Room Makeovers", "Relaxing Gameplay", "Progressive Levels"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.7,
    downloads: "12K+",
  },
  {
    id: 6,
    slug: "jungle-fury",
    icon: "/icons/jungle  Fury.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.eraflip.junglefury",
    youtubeUrl: null, // TODO: add trailer link
    title: "Jungle Fury",
    genre: "2D Platformer",
    categories: ["Action", "Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Jungle Fury/${n}.webp`),
    description: "Escape an erupting volcano — climb ancient totems, dodge falling rocks and outrun rising lava in this vertical platformer.",
    features: ["Vertical Climber", "Lava Escape", "Reflex Test", "50+ Levels"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.7,
    downloads: "10K+",
  },
  {
    id: 7,
    slug: "mtb-downhill-bike-race",
    icon: "/icons/MTB Downhill Bike Race Xtreme.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.Eraflip.UrbanDescentPOV",
    youtubeUrl: null, // TODO: add trailer link
    title: "MTB Downhill Bike Race",
    genre: "Racing",
    categories: ["Racing", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/MTB Downhill Bike Race Xtreme/${n}.webp`),
    description: "Bomb down rugged mountain trails at breakneck speed — master jumps, tight corners and realistic bike physics across scenic downhill tracks.",
    features: ["Realistic Bike Physics", "Scenic Trails", "Trick System", "Time Trials"],
    platforms: ["Mobile", "PC"],
    tech: ["Unity", "C++"],
    status: "Live",
    rating: 4.6,
    downloads: "7K+",
  },
  {
    id: 8,
    slug: "real-gun-sound-simulator",
    icon: "/icons/Real Gun Sound.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.RealGunSoundSimulator",
    youtubeUrl: null, // TODO: add trailer link
    title: "Real Gun Sound Simulator",
    genre: "Simulation",
    categories: ["Action", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Real Gun Sound Simulator/${n}.webp`),
    description: "Explore a realistic arsenal of firearms with authentic sound design, detailed 3D models and interactive customization.",
    features: ["Authentic Sound FX", "Detailed 3D Models", "Weapon Customization", "Interactive Range"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.5,
    downloads: "15K+",
  },
  {
    id: 9,
    slug: "road-rush-traffic-jam-puzzle",
    icon: "/icons/Road Rush.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.BusEscapeParkingJamGame",
    youtubeUrl: null, // TODO: add trailer link
    title: "Road Rush: Traffic Jam Puzzle",
    genre: "Puzzle",
    categories: ["RPG", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Road Rush Traffic Jam Puzzle/${n}.webp`),
    description: "Untangle gridlocked traffic jams by sliding cars and trucks out of the way in this brain-teasing puzzle adventure with hundreds of levels.",
    features: ["Brain-Teasing Puzzles", "Hundreds of Levels", "Vehicle Variety", "Progressive Difficulty"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.6,
    downloads: "9K+",
  },
  {
    id: 10,
    slug: "summit-peak",
    icon: "/icons/Summit Peak.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.Eraflip.SummitPeakOffroad",
    youtubeUrl: null, // TODO: add trailer link
    title: "Summit Peak",
    genre: "Adventure",
    categories: ["Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Summit Peak Offroad/${n}.webp`),
    description: "Climb treacherous mountain peaks, manage stamina and equipment, and conquer breathtaking summits in this atmospheric climbing adventure.",
    features: ["Atmospheric Visuals", "Stamina Management", "Gear Progression", "Breathtaking Vistas"],
    platforms: ["Mobile", "PC"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.7,
    downloads: "6K+",
  },
  {
    id: 11,
    slug: "teacher-simulator",
    icon: "/icons/High Scool Teacher Life.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.HighSchoolTeacherLifeGames",
    youtubeUrl: null, // TODO: add trailer link
    title: "Teacher Simulator",
    genre: "Simulation",
    categories: ["Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/High School Teacher Life Games/${n}.webp`),
    description: "Step into the classroom, manage mischievous students, teach lessons and keep order in this funny and chaotic simulation game.",
    features: ["Classroom Management", "Quirky Characters", "Mini-Games", "Comedic Scenarios"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.5,
    downloads: "11K+",
  },
  {
    id: 12,
    slug: "brick-arrow-escape-puzzle",
    icon: "/icons/Brick Arrow.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.Eraflip.BrickArrowEscapePuzzle",
    youtubeUrl: null, // TODO: add trailer link
    title: "Brick Arrow: Escape Puzzle",
    genre: "Puzzle",
    categories: ["Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Brick Arrow Escape Puzzle/${n}.webp`),
    description: "Place directional arrows to guide a moving brick to the finish while avoiding obstacles and dead ends, with new mechanics every level.",
    features: ["Logic Puzzles", "New Mechanics Each Level", "Progressive Difficulty", "Casual Play"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 4.1,
    downloads: "10+",
  },
  {
    id: 13,
    slug: "jumpy-tails",
    icon: "/icons/Jumpy Tail.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.JumpyTails",
    youtubeUrl: null, // TODO: add trailer link
    title: "Jumpy Tails",
    genre: "Endless Runner",
    categories: ["Action", "Adventure", "Mobile"],
    screenshots: [1, 2, 3, 4, 5, 6, 7].map((n) => `/Webp/Jumpy Tails/${n}.webp`),
    description: "Pick an adorable animal, dash through colorful worlds, grab power-ups and dodge obstacles in this fast-paced 2D endless runner.",
    features: ["Cute Animal Characters", "Multiple Environments", "Power-Ups", "Endless Gameplay"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    downloads: "1K+",
  },
  {
    id: 14,
    slug: "rest-stop-tycoon",
    icon: "/icons/Rest Stop Tycoon.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.RestStopTycoon",
    youtubeUrl: null, // TODO: add trailer link
    title: "Rest Stop Tycoon",
    genre: "Idle Tycoon",
    categories: ["Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Rest Stop Tycoon/${n}.webp`),
    description: "Build and manage your own roadside rest stop — construct shops, attract customers, boost spending and rebirth to grow faster.",
    features: ["Idle Progression", "Shop Building", "Rebirth System", "Business Management"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    rating: 2.9,
    downloads: "10+",
  },
  {
    id: 15,
    slug: "keyboard-asmr-speed-escape",
    icon: "/icons/Speed ASMR Keyboard.webp",
    playStore: "https://play.google.com/store/apps/details?id=com.EraFlip.SpeedASMRKeyboardEscape",
    youtubeUrl: null, // TODO: add trailer link
    title: "Keyboard ASMR Speed Escape",
    genre: "Runner",
    categories: ["Action", "Mobile"],
    screenshots: [1, 2, 3, 4, 5].map((n) => `/Webp/Speed ASMR Keyboard Escape/${n}.webp`),
    description: "Race across giant candy and chocolate keyboards, collect speed boosts and escape obstacles with oddly satisfying ASMR visuals and sounds.",
    features: ["ASMR Visuals & Sound", "Speed Boosts", "Pick-Up-and-Play", "Satisfying Runs"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Live",
    downloads: "50+",
  },
  {
    id: 16,
    slug: "steal-an-egg",
    icon: "/icons/Steal and Egg.webp",
    playStore: null,
    youtubeUrl: null, // TODO: add trailer link
    title: "Steal An Egg",
    genre: "Casual",
    categories: ["Adventure", "Mobile"],
    screenshots: ["/icons/Steal and Egg.webp"],
    description: "Collect, hatch and steal eggs to build your pet collection — earn money from pets, upgrade your base and discover rare mutations.",
    features: ["Egg Hatching", "Rare Pets & Mutations", "Base Upgrades", "Treadmill Training"],
    platforms: ["Mobile"],
    tech: ["Unity"],
    status: "Coming Soon",
  },
];

export const pipeline = [
  { title: "Concept", desc: "Ideation, market research and core game-loop design." },
  { title: "Design", desc: "Level design, art direction and character concepts." },
  { title: "Development", desc: "Engine setup, systems programming and asset integration." },
  { title: "Multiplayer", desc: "Netcode, matchmaking and live-service infrastructure." },
  { title: "Testing", desc: "QA passes, performance profiling and device compatibility." },
  { title: "Launch", desc: "Store submission, marketing rollout and post-launch support." },
];

export const stats = [
  { label: "Games Created", value: 50, suffix: "+" },
  { label: "Downloads", value: 10, suffix: "M+" },
  { label: "Countries", value: 20, suffix: "+" },
  { label: "Happy Clients", value: 100, suffix: "+" },
];

export const getGameBySlug = (slug) => games.find((g) => g.slug === slug);
